# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: svc-loja
#   name: svc-loja
# spec:
#   ports:
#     - port: 8080
#       protocol: TCP
# #      targetPort: 8080
#       nodePort: 31300
#   selector:
#     app: lojadeployment
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-loja
  name: svc-loja
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: techbalance
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#      nodePort: 31300
  selector:
    app: lojadeployment
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb